name: Lint

on: [push, pull_request]

jobs:
  py-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: --check .
